from __future__ import annotations


def build_methodology_text(*, native_engine_name: str, segmented_engine_name: str, two_phase_engine_name: str) -> str:
    return (
        "HESAPLAMA METODOLOJİSİ VE STANDARTLAR\n\n"
        "Bu program, basınçlı sistemlerin (boru hattı, tank, kap) güvenli tahliyesini "
        "uluslararası endüstri standartlarına (API) göre analiz eder. Temel çalışma "
        "prensipleri aşağıda özetlenmiştir:\n\n"
        "1. API 520 (PSV/Vana Boyutlandırma)\n"
        "------------------------------------\n"
        "PSV modu, API 520-1'e göre Gas/Vapor, Steam ve Liquid servislerinde ön boyutlandırma yapar.\n"
        "- Set pressure, allowable overpressure ve atmosfer basıncı kullanılarak relieving pressure (P1) kurulur.\n"
        "- Gas/Vapor için kritik akışta API 520-1 Eq. (9), subkritik akışta Eq. (19) ve Eq. (22) yaklaşımı kullanılır.\n"
        "- Steam için Eq. (26) + Napier KN + Table 13 KSH uygulanır; tablo dışı durumlarda gas/vapor fallback kullanılır.\n"
        "- Liquid için Eq. (33) ve gerekiyorsa Eq. (34)/(37) ile viscosity correction uygulanır.\n"
        "- Conventional, balanced bellows ve pilot-operated vana tipleri için backpressure mantığı servis tipine göre ayrıştırılır.\n"
        "- API 526 seçiminde built-in vendor veri modeli şimdilik yalnız Gas/Vapor servis için ek screening sağlar.\n"
        "- Built-in katalog örnek veridir; gerçek final seçim için vendor datasheet ve ASME Section XIII doğrulaması ayrıca gerekir.\n\n"
        "2. API 521 (Depressurization / Blowdown)\n"
        "------------------------------------\n"
        "Blowdown modu, zaman bağlı depressuring davranışını alternatif motorlarla çözer.\n"
        f"- {native_engine_name}, enerji dengesi ve iç ısı transferi ile tek-hacim blowdown çözümü yapar.\n"
        f"- {segmented_engine_name}, pipeline'i seri bağlı kontrol hacimlerine bölerek line-pack etkisini screening seviyesinde temsil eder.\n"
        f"- {two_phase_engine_name}, homogeneous-equilibrium esaslı screening yapar; quality ve akış rejimi özeti üretir ancak tam validated two-phase solver değildir.\n"
        "- HydDown motoru, ayrı bir kütüphane üzerinden vessel/pipeline geometrisi ile transient çözüm üretir.\n"
        "- Her iki motor da hedef basınca iniş süresine göre gerekli tahliye alanını iteratif olarak bulur.\n"
        "- API 521 fire case seçeneği aktifse hedef, screening seviyesinde 50% design pressure / 15 min kuralından türetilir; open-pool-fire heat input kabulü ayrı satırda raporlanır.\n"
        "- MDMT ve sıcaklık profilleri screening amaçlıdır; yangın, validated two-phase ve dağıtılmış boru hattı transientleri için ileri doğrulama gerekebilir.\n\n"
        "3. API 2000 (Tank Havalandırma)\n"
        "------------------------------------\n"
        "Alçak basınçlı (≤ 15 psig) depolama tanklarının 'nefes alması' için gereksinimleri hesaplar.\n"
        "- Isıl Nefes Alma: Gece soğuması (Inbreathing) veya gündüz ısınması (Outbreathing) sonucu oluşan "
        "vakum veya basınç etkisi C-Faktörü ve enlem bilgisiyle hesaplanır.\n"
        "- Pompalama Etkisi: Tanktan sıvı çekilmesi veya tanka sıvı doldurulması sırasında gaz hacmindeki "
        "hızlı değişimler kütle koruması prensibiyle eklenir.\n\n"
        "- Emergency venting seçeneği screening seviyesinde pool-fire heat input + latent-heat vaporization yaklaşımı kullanır; final API 2000 fire design yerine geçmez.\n\n"
        "4. Termofiziksel Özellikler (CoolProp)\n"
        "------------------------------------\n"
        "Programdaki tüm gaz özellikleri (yoğunluk, entalpi, viskozite, Z-faktörü) 'CoolProp' kütüphanesi "
        "aracılığıyla gerçek gaz denklemleriyle çözülür. Bu sayede ideal gaz varsayımı yerine, yüksek "
        "basınçlardaki gerçek davranışlar doğru yansıtılır.\n\n"
        "DİKKAT: Bu araç bir mühendislik asistanıdır. Kritik tasarımlarda sonuçların resmi API "
        "standartlarıyla ve uzman görüşüyle teyit edilmesi tavsiye edilir."
    )
