from __future__ import annotations


def build_methodology_text(*, native_engine_name: str, segmented_engine_name: str, two_phase_engine_name: str) -> str:
    return (
        "HESAPLAMA METODOLOJISI VE STANDARTLAR\n\n"
        "Bu program, basincli sistemlerin (boru hatti, tank, kap) guvenli tahliyesini "
        "uluslararasi endustri standartlarina (API) gore analiz eder. Temel calisma "
        "prensipleri asagida ozetlenmistir:\n\n"
        "1. API 520 (PSV/Vana Boyutlandirma)\n"
        "------------------------------------\n"
        "PSV modu, API 520-1'e gore Gas/Vapor, Steam ve Liquid servislerinde on boyutlandirma yapar.\n"
        "- Set pressure, allowable overpressure ve atmosfer basinci kullanilarak relieving pressure (P1) kurulur.\n"
        "- Gas/Vapor icin kritik akista API 520-1 Eq. (9), subkritik akista Eq. (19) ve Eq. (22) yaklasimi kullanilir.\n"
        "- Steam icin Eq. (26) + Napier KN + Table 13 KSH uygulanir; tablo disi durumlarda gas/vapor fallback kullanilir.\n"
        "- Liquid icin Eq. (33) ve gerekiyorsa Eq. (34)/(37) ile viscosity correction uygulanir.\n"
        "- Steam ve Liquid servisleri icin istege bagli psvpy cross-check calistirilabilir; native sizing sonucu birincil hesap olarak korunur.\n"
        "- Conventional, balanced bellows ve pilot-operated vana tipleri icin backpressure mantigi servis tipine gore ayristirilir.\n"
        "- API 526 seciminde built-in vendor veri modeli simdilik yalniz Gas/Vapor servis icin ek screening saglar.\n"
        "- Built-in katalog ornek veridir; gercek final secim icin vendor datasheet ve ASME Section XIII dogrulamasi ayrica gerekir.\n\n"
        "2. API 521 (Depressurization / Blowdown)\n"
        "------------------------------------\n"
        "Blowdown modu, zaman bagli depressuring davranisini alternatif motorlarla cozer.\n"
        f"- {native_engine_name}, enerji dengesi ve ic isi transferi ile tek-hacim blowdown cozumu yapar.\n"
        f"- {segmented_engine_name}, pipeline'i seri bagli kontrol hacimlerine bolerek line-pack etkisini screening seviyesinde temsil eder.\n"
        f"- {two_phase_engine_name}, homogeneous-equilibrium esasli screening yapar; quality ve akis rejimi ozeti uretir ancak tam validated two-phase solver degildir.\n"
        "- HydDown motoru, ayri bir kutuphane uzerinden vessel/pipeline geometrisi ile transient cozum uretir.\n"
        "- Her iki motor da hedef basinca inis suresine gore gerekli tahliye alanini iteratif olarak bulur.\n"
        "- API 521 fire case secenegi aktifse hedef, screening seviyesinde 50% design pressure / 15 min kuralindan turetilir; open-pool-fire heat input kabulu ayri satirda raporlanir.\n"
        "- MDMT ve sicaklik profilleri screening amaclidir; yangin, validated two-phase ve dagitilmis boru hatti transientleri icin ileri dogrulama gerekebilir.\n\n"
        "3. API 2000 (Tank Havalandirma)\n"
        "------------------------------------\n"
        "Alcak basincli (<= 15 psig) depolama tanklarinin nefes almasi icin gereksinimleri hesaplar.\n"
        "- Isil nefes alma: Gece sogumasi (Inbreathing) veya gunduz isinmasi (Outbreathing) sonucu olusan vakum veya basinc etkisi C-faktoru ve enlem bilgisiyle hesaplanir.\n"
        "- Pompalama etkisi: Tanktan sivi cekilmesi veya tanka sivi doldurulmasi sirasinda gaz hacmindeki hizli degisimler kutle korumasi prensibiyle eklenir.\n"
        "- Emergency venting secenegi screening seviyesinde pool-fire heat input + latent-heat vaporization yaklasimi kullanir; final API 2000 fire design yerine gecmez.\n\n"
        "4. Termofiziksel Ozellikler (CoolProp)\n"
        "------------------------------------\n"
        "Programdaki tum gaz ozellikleri (yogunluk, entalpi, viskozite, Z-faktoru) CoolProp kutuphanesi araciligiyla gercek gaz denklemleriyle cozulur. "
        "Bu sayede ideal gaz varsayimi yerine, yuksek basinclardaki gercek davranislar daha dogru yansitilir.\n\n"
        "DIKKAT: Bu arac bir muhendislik asistanidir. Kritik tasarimlarda sonuclarin resmi API standartlariyla ve uzman gorusuyle teyit edilmesi tavsiye edilir."
    )
